name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: mkdocs-material-
        env:
          cache_id: ${{ github.run_id }}

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-glightbox

      - name: Build site
        run: mkdocs build --clean

      - name: Fix file permissions
        run: |
          chmod -c -R +rX site/ | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
